# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knit < Formula
  desc "Language & schema agnostic code generation toolkit"
  homepage "https://github.com/knitcodegen/knit"
  version "0.4.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/knitcodegen/knit/releases/download/v0.4.1-alpha/knit_darwin_amd64.tar.gz"
      sha256 "77187ac5ef5edce2dcc013f0a28b796ded78dd19c4fba12097a7c468b9c8a0b1"

      def install
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/knitcodegen/knit/releases/download/v0.4.1-alpha/knit_darwin_arm64.tar.gz"
      sha256 "494a53393c7968b598fa8a8ce8984a1e7f2a07478859b7a37dd78bdb09924a5e"

      def install
        bin.install "knit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/knitcodegen/knit/releases/download/v0.4.1-alpha/knit_linux_arm64.tar.gz"
      sha256 "efc2180483cf2349d09bbc844879edfa97f453d89fdbe1d25d87109b2894a87a"

      def install
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/knitcodegen/knit/releases/download/v0.4.1-alpha/knit_linux_arm.tar.gz"
      sha256 "60387bd23e33d6acd56df74a6af8abe7dc68e11dd90f4df85ae29e4129c9173c"

      def install
        bin.install "knit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/knitcodegen/knit/releases/download/v0.4.1-alpha/knit_linux_amd64.tar.gz"
      sha256 "b62d3cd8b85d2396febd0f5d6895fd2bbad225253506fdf676bf6d492ff7482a"

      def install
        bin.install "knit"
      end
    end
  end

  test do
    system "#{bin}/knit", "--help"
  end
end
