# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knit < Formula
  desc "Language & schema agnostic code generation toolkit"
  homepage "https://github.com/knitcodegen/knit"
  version "0.2.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/knitcodegen/knit/releases/download/v0.2.1-alpha/knit_darwin_amd64.tar.gz"
      sha256 "4324f25b024b056694bda450863ae714039cf3df96d6747b90932b59b1d9f817"

      def install
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/knitcodegen/knit/releases/download/v0.2.1-alpha/knit_darwin_arm64.tar.gz"
      sha256 "f9eacdd41c6e65b0546bc2beca6f47255191b807d7b3498351ce41543458aed6"

      def install
        bin.install "knit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/knitcodegen/knit/releases/download/v0.2.1-alpha/knit_linux_arm64.tar.gz"
      sha256 "972868760843071b7f83ee58d77e0eb834321a4bdc07f969e57ef8986d609769"

      def install
        bin.install "knit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/knitcodegen/knit/releases/download/v0.2.1-alpha/knit_linux_amd64.tar.gz"
      sha256 "aa0043a980a198a4af2c786b5e06a2e7112af770c5454a8f233b7ab9637da0c1"

      def install
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/knitcodegen/knit/releases/download/v0.2.1-alpha/knit_linux_arm.tar.gz"
      sha256 "a2e8cb9d61ac13d4e52c857ee17f7719f44a9757c159673488c3f57f98b37570"

      def install
        bin.install "knit"
      end
    end
  end

  test do
    system "#{bin}/knit", "--help"
  end
end
